apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}
spec:
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: http
    - port: 8080
      name: http-dev
      protocol: TCP
      targetPort: http
  selector:
    release: {{.Release.Name}}
